const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./endpoints.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5001",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account",
      },
    },
  },
  definitions: {
    User: {
      userName: "Jhon Doe",
      userEmail: "JhonDoe@epitech.eu",
    },
    AddUser: {
      $username: "Jhon Doe",
      $email: "JhonDoe@epitech.eu",
      password: "password",
    },
    AllUser: {
      $result: [
        {
          id: 1,
          username: "Jhon Doe",
          email: "JhonDoe@epitech.eu",
          password: "password",
        },
      ],
    },
    UserByName: {
      $result: [
        {
          id: 1,
          username: "Jhon Doe",
          email: "JhonDoe@epitech.eu",
          password: "password",
        },
      ],
    },
    Cards: {
      result: [
        {
          id: 15,
          name: "cat",
          groupsId: 13,
        },
      ],
    },
    Organizations: {
      result: [
        {
          id: 36,
          organizationName: "Epitech",
        },
      ],
    },
    UserOrganization: [
      {
        userId: 104,
        organizationId: 38,
        organizationName: "Adapei",
      },
    ],
    OrganizationUser: [
      {
        userId: 104,
        organizationId: 38,
        organizationName: "Adapei",
      },
    ],
    Groups: {
      result: [
        {
          id: 36,
          name: "food",
          organizationName: "Epitech",
        },
      ],
    },
    CreateGroup: {
      groupeName: "Jean",
      organizationId: 18,
    },
    CreateOrga: {
      organizationName: "Epi",
    },
    AddUserOrga: {
      userId: 104,
      organizationId: 19,
      organizationName: "Epitech",
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app.js");
});
